server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: development
  application:
    name: ShareNoteX
     
  datasource:
    url: jdbc:sqlserver://sharif12.database.windows.net:1433;database=gameinventory;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: iamsharif
    password: Iamdexter@2024
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
   
      
SECRET_KEY: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
---

spring:
  config:
    activate:
      on-profile: development
         
  jpa:
    show-sql: true
    
com:
  keycloak:
    server:
      url: http://localhost:8080
    master:
      realm: master
      clientId: admin-cli
    admin:
      username: Sharif
      password: 110062
    user:
      realm: Security
    config:
      clientId: Speer
      secret: yZbq4g3D71RmKcrFaNAqK2LhSfZ2uG6o

---

spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false

